using System.Linq;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Logging.Testing;
using Saunter.Options;
using Shouldly;
using Xunit;

namespace Saunter.Tests
{
    public class AsyncApiEndpointRouteBuilderExtensionsTests
    {
        [Fact]
        public void MapAsyncApiEndpoints_UsesConfiguredDocumentRoutes()
        {
            var builder = WebApplication.CreateBuilder();
            builder.Services.AddAsyncApiSchemaGeneration(ScopeScanToThisFixture);
            builder.Services.ConfigureAsyncApiDocument("orders", document =>
            {
                document.AttributeDocumentName = "v1";
            });

            using var app = builder.Build();

            app.MapAsyncApiDocuments();
            app.MapAsyncApiUi();

            var routes = ((IEndpointRouteBuilder)app).DataSources
                .SelectMany(dataSource => dataSource.Endpoints)
                .OfType<RouteEndpoint>()
                .Select(endpoint => endpoint.RoutePattern.RawText)
                .Where(route => route != null)
                .ToArray();

            routes.ShouldContain("/asyncapi/orders/asyncapi.json");
            routes.ShouldContain("/asyncapi/orders/asyncapi.yaml");
            routes.ShouldContain("/asyncapi/orders/ui");
            routes.ShouldContain("/asyncapi/orders/ui/index.html");
            routes.ShouldContain("/asyncapi/orders/ui/{assetName}");
            routes.ShouldNotContain("/asyncapi/{document}/asyncapi.json");
        }

        [Fact]
        public void MapAsyncApi_MapsDocumentsAndUi()
        {
            var builder = WebApplication.CreateBuilder();
            builder.Services.AddAsyncApiSchemaGeneration(ScopeScanToThisFixture);
            builder.Services.ConfigureAsyncApiDocument("orders", document =>
            {
                document.AttributeDocumentName = "v1";
            });

            using var app = builder.Build();

            app.MapAsyncApi();

            var routes = ((IEndpointRouteBuilder)app).DataSources
                .SelectMany(dataSource => dataSource.Endpoints)
                .OfType<RouteEndpoint>()
                .Select(endpoint => endpoint.RoutePattern.RawText)
                .ToArray();

            routes.ShouldContain("/asyncapi/orders/asyncapi.json");
            routes.ShouldContain("/asyncapi/orders/asyncapi.yaml");
            routes.ShouldContain("/asyncapi/orders/ui");
            routes.ShouldContain("/asyncapi/orders/ui/index.html");
            routes.ShouldContain("/asyncapi/orders/ui/{assetName}");
        }

        [Fact]
        public void MapAsyncApiUi_ForStaticDocument_MapsUiWithoutARegistration()
        {
            var builder = WebApplication.CreateBuilder();
            builder.Services.AddAsyncApiSchemaGeneration(ScopeScanToThisFixture);

            using var app = builder.Build();

            // No ConfigureAsyncApiDocument call: the document is served by the host
            // (e.g. build-time generated bytes), and only the UI comes from Saunter.
            app.MapAsyncApiUi("/asyncapi/v1/ui", "/asyncapi/v1/asyncapi.json", "Orders API");

            var routes = ((IEndpointRouteBuilder)app).DataSources
                .SelectMany(dataSource => dataSource.Endpoints)
                .OfType<RouteEndpoint>()
                .Select(endpoint => endpoint.RoutePattern.RawText)
                .ToArray();

            routes.ShouldContain("/asyncapi/v1/ui");
            routes.ShouldContain("/asyncapi/v1/ui/index.html");
            routes.ShouldContain("/asyncapi/v1/ui/{assetName}");

            // The caller owns the document routes; this overload must not map them.
            routes.ShouldNotContain("/asyncapi/v1/asyncapi.json");
            routes.ShouldNotContain("/asyncapi/v1/asyncapi.yaml");
        }

        [Fact]
        public void MapAsyncApiUi_ForStaticDocument_TrimsTrailingSlashFromBaseRoute()
        {
            var builder = WebApplication.CreateBuilder();
            builder.Services.AddAsyncApiSchemaGeneration(ScopeScanToThisFixture);

            using var app = builder.Build();

            app.MapAsyncApiUi("/asyncapi/v1/ui/", "/asyncapi/v1/asyncapi.json");

            var routes = ((IEndpointRouteBuilder)app).DataSources
                .SelectMany(dataSource => dataSource.Endpoints)
                .OfType<RouteEndpoint>()
                .Select(endpoint => endpoint.RoutePattern.RawText)
                .ToArray();

            routes.ShouldContain("/asyncapi/v1/ui");
            routes.ShouldContain("/asyncapi/v1/ui/index.html");
            routes.ShouldNotContain("/asyncapi/v1/ui//index.html");
        }

        [Fact]
        public void MapAsyncApiUi_ForStaticDocument_CoexistsWithRegisteredDocuments()
        {
            var builder = WebApplication.CreateBuilder();
            builder.Services.AddAsyncApiSchemaGeneration(ScopeScanToThisFixture);
            builder.Services.ConfigureAsyncApiDocument("markus-config", document =>
            {
                document.AttributeDocumentName = "v1";
            });

            using var app = builder.Build();

            // The runtime-generated document keeps its own routes; the static one adds only a UI.
            app.MapAsyncApi();
            app.MapAsyncApiUi("/asyncapi/v2/ui", "/asyncapi/v2/asyncapi.json");

            var routes = ((IEndpointRouteBuilder)app).DataSources
                .SelectMany(dataSource => dataSource.Endpoints)
                .OfType<RouteEndpoint>()
                .Select(endpoint => endpoint.RoutePattern.RawText)
                .ToArray();

            routes.ShouldContain("/asyncapi/markus-config/asyncapi.json");
            routes.ShouldContain("/asyncapi/markus-config/ui");
            routes.ShouldContain("/asyncapi/v2/ui");
            routes.ShouldContain("/asyncapi/v2/ui/{assetName}");
        }

        [Theory]
        [InlineData("/asyncapi/v1/asyncapi.json", "/asyncapi/v1/asyncapi.yaml")]
        [InlineData("/asyncapi/asyncapi.JSON", "/asyncapi/asyncapi.yaml")]
        [InlineData("/asyncapi/v1/ui", null)]
        [InlineData(null, null)]
        public void DeriveYamlRoute_SwapsJsonSuffix(string jsonRoute, string expected)
        {
            AsyncApiEndpointRouteBuilderExtensions.DeriveYamlRoute(jsonRoute).ShouldBe(expected);
        }

        [Fact]
        public void MapAsyncApiDocuments_LogsMappedRoutes()
        {
            var builder = WebApplication.CreateBuilder();
            builder.Services.AddFakeLogging();
            builder.Services.AddAsyncApiSchemaGeneration(ScopeScanToThisFixture);
            builder.Services.ConfigureAsyncApiDocument("orders", document =>
            {
                document.AttributeDocumentName = "v1";
            });

            using var app = builder.Build();

            app.MapAsyncApiDocuments();

            var collector = app.Services.GetRequiredService<FakeLogCollector>();
            collector.GetSnapshot().ShouldContain(record =>
                record.Message.Contains("AsyncAPI document 'orders' mapped at /asyncapi/orders/asyncapi.json"));
        }

        /// <summary>
        /// These tests assert on mapped routes, not on generated content, so the scan is pinned
        /// to a fixture-local marker. Without a marker Saunter falls back to scanning the entry
        /// assembly — here the test assembly — which picks up the deliberately conflicting
        /// annotated fixtures other tests declare and throws during document generation.
        /// </summary>
        private static void ScopeScanToThisFixture(AsyncApiOptions options)
        {
            options.AssemblyMarkerTypes = new[] { typeof(NoAnnotatedTypesMarker) };
        }

        private sealed class NoAnnotatedTypesMarker
        {
        }
    }
}
